apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloopperators.terry.com
spec:
  scope: Namespaced
  group: terry.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
       openAPIV3Schema:
          type: object
  names:
    kind: HelloOperator
    plural: helloopperators
    singular: hellooperator
    shortNames:
      - helloop
  
